package org.cyberwarriors.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JobExecutionReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobExecutionReportAllPropertiesEquals(JobExecutionReport expected, JobExecutionReport actual) {
        assertJobExecutionReportAutoGeneratedPropertiesEquals(expected, actual);
        assertJobExecutionReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobExecutionReportAllUpdatablePropertiesEquals(JobExecutionReport expected, JobExecutionReport actual) {
        assertJobExecutionReportUpdatableFieldsEquals(expected, actual);
        assertJobExecutionReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobExecutionReportAutoGeneratedPropertiesEquals(JobExecutionReport expected, JobExecutionReport actual) {
        assertThat(actual)
            .as("Verify JobExecutionReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobExecutionReportUpdatableFieldsEquals(JobExecutionReport expected, JobExecutionReport actual) {
        assertThat(actual)
            .as("Verify JobExecutionReport relevant properties")
            .satisfies(a -> assertThat(a.getStartTime()).as("check startTime").isEqualTo(expected.getStartTime()))
            .satisfies(a -> assertThat(a.getEndTime()).as("check endTime").isEqualTo(expected.getEndTime()))
            .satisfies(a -> assertThat(a.getExecutionNode()).as("check executionNode").isEqualTo(expected.getExecutionNode()))
            .satisfies(a -> assertThat(a.getExecutionLog()).as("check executionLog").isEqualTo(expected.getExecutionLog()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobExecutionReportUpdatableRelationshipsEquals(JobExecutionReport expected, JobExecutionReport actual) {
        assertThat(actual)
            .as("Verify JobExecutionReport relationships")
            .satisfies(a -> assertThat(a.getJobRequest()).as("check jobRequest").isEqualTo(expected.getJobRequest()));
    }
}
