package org.cyberwarriors.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JobRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobRequestAllPropertiesEquals(JobRequest expected, JobRequest actual) {
        assertJobRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertJobRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobRequestAllUpdatablePropertiesEquals(JobRequest expected, JobRequest actual) {
        assertJobRequestUpdatableFieldsEquals(expected, actual);
        assertJobRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobRequestAutoGeneratedPropertiesEquals(JobRequest expected, JobRequest actual) {
        assertThat(actual)
            .as("Verify JobRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobRequestUpdatableFieldsEquals(JobRequest expected, JobRequest actual) {
        assertThat(actual)
            .as("Verify JobRequest relevant properties")
            .satisfies(a -> assertThat(a.getFileContent()).as("check fileContent").isEqualTo(expected.getFileContent()))
            .satisfies(a ->
                assertThat(a.getFileContentContentType())
                    .as("check fileContent contenty type")
                    .isEqualTo(expected.getFileContentContentType())
            )
            .satisfies(a -> assertThat(a.getScore()).as("check score").isEqualTo(expected.getScore()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getFileType()).as("check fileType").isEqualTo(expected.getFileType()))
            .satisfies(a -> assertThat(a.getRequestType()).as("check requestType").isEqualTo(expected.getRequestType()))
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobRequestUpdatableRelationshipsEquals(JobRequest expected, JobRequest actual) {
        // empty method
    }
}
