package org.cyberwarriors.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JobReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobReportAllPropertiesEquals(JobReport expected, JobReport actual) {
        assertJobReportAutoGeneratedPropertiesEquals(expected, actual);
        assertJobReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobReportAllUpdatablePropertiesEquals(JobReport expected, JobReport actual) {
        assertJobReportUpdatableFieldsEquals(expected, actual);
        assertJobReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobReportAutoGeneratedPropertiesEquals(JobReport expected, JobReport actual) {
        assertThat(actual)
            .as("Verify JobReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobReportUpdatableFieldsEquals(JobReport expected, JobReport actual) {
        assertThat(actual)
            .as("Verify JobReport relevant properties")
            .satisfies(a -> assertThat(a.getReportDate()).as("check reportDate").isEqualTo(expected.getReportDate()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getIsSuccessful()).as("check isSuccessful").isEqualTo(expected.getIsSuccessful()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobReportUpdatableRelationshipsEquals(JobReport expected, JobReport actual) {
        assertThat(actual)
            .as("Verify JobReport relationships")
            .satisfies(a -> assertThat(a.getJobRequest()).as("check jobRequest").isEqualTo(expected.getJobRequest()));
    }
}
