package org.cyberwarriors.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SanitizationReportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSanitizationReportAllPropertiesEquals(SanitizationReport expected, SanitizationReport actual) {
        assertSanitizationReportAutoGeneratedPropertiesEquals(expected, actual);
        assertSanitizationReportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSanitizationReportAllUpdatablePropertiesEquals(SanitizationReport expected, SanitizationReport actual) {
        assertSanitizationReportUpdatableFieldsEquals(expected, actual);
        assertSanitizationReportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSanitizationReportAutoGeneratedPropertiesEquals(SanitizationReport expected, SanitizationReport actual) {
        assertThat(actual)
            .as("Verify SanitizationReport auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSanitizationReportUpdatableFieldsEquals(SanitizationReport expected, SanitizationReport actual) {
        assertThat(actual)
            .as("Verify SanitizationReport relevant properties")
            .satisfies(a -> assertThat(a.getReportDate()).as("check reportDate").isEqualTo(expected.getReportDate()))
            .satisfies(a -> assertThat(a.getDetails()).as("check details").isEqualTo(expected.getDetails()))
            .satisfies(a -> assertThat(a.getIsSuccessful()).as("check isSuccessful").isEqualTo(expected.getIsSuccessful()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSanitizationReportUpdatableRelationshipsEquals(SanitizationReport expected, SanitizationReport actual) {
        assertThat(actual)
            .as("Verify SanitizationReport relationships")
            .satisfies(a -> assertThat(a.getJobRequest()).as("check jobRequest").isEqualTo(expected.getJobRequest()));
    }
}
